image: webdevops/php-apache-dev:7.4

pipelines:
  pull-requests:
    '**':
      - step:
          name: Unit Test
          script:
            - echo "Start to preparing environment"
            - composer install
            - echo "Run tests"
            - userEmail=$userEmail userPass=$userPass ./vendor/bin/phpunit --configuration phpunit.xml tests/Feature --no-coverage
      - step:
          name: PHPStan analyse
          script:
            - echo "Start to preparing environment"
            - composer install
            - echo "Run PhpStan analyse with level 0 (basic)"
            - vendor/bin/phpstan analyse -l 0 src/ tests/