version: '3.3'
services:
  apissoutil:
    image: webdevops/php-apache-dev:7.3
    container_name: api-sso-util
    restart: always
    user: application
    environment:
      - WEB_ALIAS_DOMAIN=api-sso-util
      - WEB_DOCUMENT_ROOT=/app
      - PHP_DATE_TIMEZONE=EST
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=2048M
      - PHP_MAX_EXECUTION_TIME=1800
      - PHP_POST_MAX_SIZE=500M
      - PHP_UPLOAD_MAX_FILESIZE=1024M
      - PHP_EXTENSION_XDEBUG=1
    volumes:
      - ./:/app
    ports:
      - "8080:80"
      - "4433:443"
      - "32822:22"
volumes:
  db-data:
    external: false