<?php


namespace SALESmanago\Model\Collections;

use SALESmanago\Entity\Event\Event;

class EventsCollection extends AbstractCollection
{
    public function add($obj)
    {
        return $this; // TODO: Change the autogenerated stub
    }
}